# Generated by Django 4.0.3 on 2022-03-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduling",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
    ]
