# Generated by Django 4.0.3 on 2022-03-24 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedule", "0005_scheduling_states"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faithfulness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client",
                    models.CharField(max_length=200, verbose_name="Nome do cliente"),
                ),
                ("level", models.IntegerField(default=0, verbose_name="Fidelidade")),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Prestador do serviço",
                    ),
                ),
            ],
        ),
    ]
