# Generated by Django 4.0.3 on 2022-03-24 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedule", "0007_alter_faithfulness_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faithfulness",
            name="client",
            field=models.CharField(max_length=200, verbose_name="Nome do cliente"),
        ),
        migrations.AlterField(
            model_name="faithfulness",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faithfulness",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Prestador do serviço",
            ),
        ),
    ]
