# Generated by Django 4.0.3 on 2022-03-27 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0010_alter_employee_establishment_alter_employee_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="establishment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="schedule.establishment",
                verbose_name="Nome do estabelecimento",
            ),
        ),
    ]
